# name: Actions Workflow
# # We can have a object format to be more explicit
# on:
#   push:
#   pull_request:
#     types: [closed, assigned, opened, reopened]
# # We format it using array.
# # on: [push, pull_request]

# jobs:
#   # Let's call it this.
#   run-github-actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: List Files
#         run: |
#           pwd
#           ls -a
#       - name: Checkout Action from Github
#         # One of the most familiar actions from github https://github.com/actions/checkout
#         # This will authenticate and fetch you specific commit who triggered this.
#         # and this will clone you repo in your virtual machine.
#         uses: actions/checkout@v3
#       - name: List all files after checking out using github chekckout actions.
#         run: |
#           pwd
#           ls -a
#       - name: Sample JS Actions
#         # We have to make an id for this step to be referenced.
#         id: greet
#         # We can reference repo with branch but not recommended.
#         # uses: /actions/hello-world-javascript-action@master
#         # We can reference repo with commit
#         # uses: /actions/hello-world-javascript-action@ad41a6c27317e688719c813b0d6a25685a9bce54
#         # We can reference repo with it's tag.
#         uses: /actions/hello-world-javascript-action@v1.1
#         # This is how we can provide an input to an action by using with
#         with:
#           # This provided by the action itself. Please check this repo
#           # https://github.com/actions/hello-world-javascript-action
#           who-to-greet: "John"
#       # Actions can also produce an output. Like this 2nd step.
#       # We can also get output from step.
#       - name: Log Greeting time
#         # Let's echo the output of the Sample JS Action step.
#         # steps is a w/c Github makes available to us. This is an object that contains all our steps.
#         # outputs.time will usually be found in the docu of actions you are using.
#         run: echo "${{ steps.greet.outputs.time }}"
            


